#!/bin/bash
# Install Path Planner
# Part of SLAM Integration Installation

set -e

PLANNER_TYPE=$1
WORKSPACE_PATH=$2
ROS_VERSION=$3

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[✓]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[⚠]${NC} $1"; }
log_error() { echo -e "${RED}[✗]${NC} $1"; }

# Detect architecture
ARCH=$(uname -m)
IS_ARM64=false
if [[ "$ARCH" == "aarch64" || "$ARCH" == "arm64" ]]; then
    IS_ARM64=true
    log_info "Detected ARM64 architecture (Jetson/embedded)"
fi

# Detect ROS distro from environment if not passed
if [[ -z "$ROS_DISTRO" ]]; then
    ROS_DISTRO="${ROS_DISTRO:-$(printenv ROS_DISTRO 2>/dev/null || echo "")}"
fi
if [[ -z "$ROS_DISTRO" ]]; then
    if [[ "$ROS_VERSION" == "ROS1" ]]; then
        ROS_DISTRO="noetic"
    else
        ROS_DISTRO="humble"
    fi
    log_warn "ROS_DISTRO not set, assuming ${ROS_DISTRO}"
fi

if [[ -z "$PLANNER_TYPE" ]]; then
    log_error "Usage: $0 <PLANNER_TYPE> <WORKSPACE_PATH> <ROS_VERSION>"
    log_info "Supported planner types: waypoint_nav, super, ommpc, rog_map, ego_planner, fuel, nav2, octomap"
    exit 1
fi

if [[ -z "$WORKSPACE_PATH" ]]; then
    log_error "WORKSPACE_PATH not specified"
    exit 1
fi

if [[ -z "$ROS_VERSION" ]]; then
    log_error "ROS_VERSION not specified (ROS1 or ROS2)"
    exit 1
fi

log_info "Installing path planner: $PLANNER_TYPE"
log_info "  Workspace: $WORKSPACE_PATH"
log_info "  ROS version: $ROS_VERSION ($ROS_DISTRO)"
log_info "  Architecture: $ARCH"
echo ""

cd "$WORKSPACE_PATH/src"

# ─────────────────────────────────────────────────────────────────────────────
# Helper: try apt install, warn gracefully on missing packages
# ─────────────────────────────────────────────────────────────────────────────
apt_install_safe() {
    local pkgs=("$@")
    local available=()
    for pkg in "${pkgs[@]}"; do
        if apt-cache show "$pkg" &> /dev/null 2>&1; then
            available+=("$pkg")
        else
            log_warn "Package not available in apt: $pkg (skipping)"
        fi
    done
    if [[ ${#available[@]} -gt 0 ]]; then
        sudo apt install -y "${available[@]}"
    fi
}

# ─────────────────────────────────────────────────────────────────────────────
# Helper: run rosdep from workspace root
# ─────────────────────────────────────────────────────────────────────────────
run_rosdep() {
    cd "$WORKSPACE_PATH"
    if command -v rosdep &> /dev/null; then
        rosdep update --rosdistro "$ROS_DISTRO" 2>/dev/null || rosdep update
        rosdep install --from-paths src --ignore-src -r -y \
            || log_warn "Some rosdep dependencies may need manual installation"
    else
        log_warn "rosdep not found — skipping automatic dependency resolution"
    fi
    cd "$WORKSPACE_PATH/src"
}

# ─────────────────────────────────────────────────────────────────────────────
case "$PLANNER_TYPE" in

    # ── 1. Waypoint Navigation ────────────────────────────────────────────────
    "waypoint_nav"|"waypoint-nav")
        log_info "Setting up waypoint_nav (MAVROS-based)..."

        if [[ "$ROS_VERSION" == "ROS1" ]]; then
            # Check if navigation stack base is already present
            if dpkg -l | grep -q "ros-${ROS_DISTRO}-navigation"; then
                log_success "ROS 1 navigation stack already installed"
            else
                log_info "Cloning ROS 1 navigation stack as base reference..."
                if [[ -d "navigation" ]]; then
                    log_success "navigation repo already cloned"
                else
                    git clone --depth 1 https://github.com/ros-planning/navigation.git
                    log_success "navigation cloned"
                fi
            fi

            # MAVROS extras for setpoint topics (core waypoint nav interface)
            log_info "Installing MAVROS extras for setpoint topics..."
            sudo apt update
            apt_install_safe "ros-${ROS_DISTRO}-mavros-extras"
        else
            # ROS 2: nav2-waypoint-follower
            if ros2 pkg list 2>/dev/null | grep -q "^nav2_waypoint_follower$"; then
                log_success "nav2_waypoint_follower already installed"
            else
                log_info "Installing nav2_waypoint_follower..."
                sudo apt update
                apt_install_safe "ros-${ROS_DISTRO}-nav2-waypoint-follower"
                log_success "nav2_waypoint_follower installed"
            fi

            log_info "Installing MAVROS extras for setpoint topics..."
            sudo apt update
            apt_install_safe "ros-${ROS_DISTRO}-mavros-extras"
        fi

        log_warn "waypoint_nav: a custom MAVROS setpoint node will be generated by the SLAM agent."
        log_warn "See: slam-agent docs for the custom waypoint publisher template."
        ;;

    # ── 2. SUPER (HKU-Mars, Safety-Assured High-Speed Navigation) ──────────
    "super"|"SUPER")
        log_info "Installing SUPER planner (HKU-Mars, Science Robotics 2025)..."
        log_info "SUPER bundles ROG-Map internally — no separate OctoMap needed."

        if [[ -d "SUPER" ]]; then
            log_success "SUPER already cloned"
        else
            log_info "Cloning SUPER with submodules (includes ROG-Map, CIRI, MARSIM)..."
            git clone --recurse-submodules https://github.com/hku-mars/SUPER.git
            log_success "SUPER cloned"
        fi

        # Select ROS version
        if [[ -f "SUPER/scripts/select_ros_version.sh" ]]; then
            if [[ "$ROS_VERSION" == "ROS1" ]]; then
                log_info "Selecting ROS 1 build..."
                bash SUPER/scripts/select_ros_version.sh ROS1
            else
                log_warn "SUPER ROS 2 support is experimental and may be unstable."
                log_info "Selecting ROS 2 build..."
                bash SUPER/scripts/select_ros_version.sh ROS2
            fi
        fi

        # ARM64: remove MARSIM OpenGL renderer (not needed on real hardware)
        if [[ "$IS_ARM64" == "true" ]]; then
            if [[ -d "SUPER/mars_uav_sim/marsim_render" ]]; then
                log_info "ARM64: removing MARSIM renderer (OpenGL, sim-only)..."
                rm -rf SUPER/mars_uav_sim/marsim_render
                log_success "MARSIM renderer removed (not needed on Jetson)"
            fi
        fi

        # Dependencies
        log_info "Installing SUPER dependencies..."
        sudo apt update
        apt_install_safe "libeigen3-dev" "libdw-dev" "libncurses5-dev" "libncursesw5-dev"

        if [[ "$ROS_VERSION" == "ROS1" ]]; then
            apt_install_safe "ros-${ROS_DISTRO}-mavros" \
                             "ros-${ROS_DISTRO}-mavros-extras" \
                             "ros-${ROS_DISTRO}-pcl-ros" \
                             "ros-${ROS_DISTRO}-rosfmt"
        else
            apt_install_safe "ros-${ROS_DISTRO}-mavros" \
                             "ros-${ROS_DISTRO}-mavros-extras" \
                             "ros-${ROS_DISTRO}-pcl-ros"
        fi

        # Eigen symlink required by SUPER
        if [[ ! -e /usr/include/Eigen ]]; then
            log_info "Creating Eigen symlink (/usr/include/Eigen → eigen3/Eigen)..."
            sudo ln -sf /usr/include/eigen3/Eigen /usr/include/Eigen
        fi

        run_rosdep
        ;;

    # ── 3. OMMPC Controller (for SUPER trajectory tracking) ────────────────
    "ommpc"|"OMMPC"|"ommpc_controller")
        log_info "Installing OMMPC controller (On-Manifold MPC for SUPER trajectory tracking)..."
        log_info "OMMPC outputs body-rate + thrust commands directly to MAVROS."

        if [[ "$ROS_VERSION" != "ROS1" ]]; then
            log_warn "OMMPC is ROS 1 Noetic only. For ROS 2, use the simple position bridge."
        fi

        if [[ -d "ommpc_controller" ]]; then
            log_success "ommpc_controller already cloned"
        else
            log_info "Cloning ommpc_controller..."
            git clone https://github.com/OliverWu515/ommpc_controller.git
            log_success "ommpc_controller cloned"
        fi

        # OSQP v0.6.3 (QP solver, required)
        log_info "Installing OSQP v0.6.3..."
        if pkg-config --exists osqp 2>/dev/null; then
            log_success "OSQP already installed"
        else
            if [[ -d "osqp" ]]; then
                log_success "OSQP source already present"
            else
                git clone --branch v0.6.3 --recurse-submodules https://github.com/osqp/osqp.git
                cmake -S osqp -B osqp/build -DCMAKE_BUILD_TYPE=Release
                cmake --build osqp/build -- -j"$(nproc)"
                sudo cmake --install osqp/build
                log_success "OSQP v0.6.3 built and installed"
            fi
        fi

        # ROS dependencies
        log_info "Installing OMMPC dependencies..."
        sudo apt update
        apt_install_safe "libeigen3-dev" "ros-${ROS_DISTRO}-ddynamic-reconfigure" \
                         "ros-${ROS_DISTRO}-mavros" "ros-${ROS_DISTRO}-mavros-extras"

        run_rosdep

        log_warn "OMMPC is PX4-native. For ArduPilot: modify mode checks (OFFBOARD → GUIDED)"
        log_warn "and tune hover_percentage for your drone. See Phase 8 docs."
        ;;

    # ── 4. ROG-Map (Standalone, without SUPER) ──────────────────────────────
    "rog_map"|"rog-map"|"ROG-Map")
        log_info "Installing ROG-Map standalone (HKU-Mars, IROS 2024)..."
        log_info "ROG-Map replaces OctoMap for real-time drone navigation."

        if [[ -d "ROG-Map" ]]; then
            log_success "ROG-Map already cloned"
        else
            log_info "Cloning ROG-Map..."
            git clone https://github.com/hku-mars/ROG-Map.git
            log_success "ROG-Map cloned"
        fi

        # ARM64: remove MARSIM examples (OpenGL x86 paths)
        if [[ "$IS_ARM64" == "true" ]]; then
            if [[ -d "ROG-Map/examples/MARSIM" ]]; then
                log_info "ARM64: removing MARSIM examples (OpenGL, sim-only)..."
                rm -rf ROG-Map/examples/MARSIM
                log_success "MARSIM examples removed (not needed on Jetson)"
            fi
        fi

        # Dependencies
        log_info "Installing ROG-Map dependencies..."
        sudo apt update
        apt_install_safe "libeigen3-dev" "libdw-dev"

        if [[ "$ROS_VERSION" == "ROS1" ]]; then
            apt_install_safe "ros-${ROS_DISTRO}-rosfmt"
        else
            log_warn "ROG-Map standalone is ROS 1. For ROS 2, install via 'super' (bundles ROG-Map)."
        fi

        run_rosdep

        log_warn "Important: deactivate conda before building (conda deactivate)"
        ;;

    # ── 4. EGO-Planner-v2 ────────────────────────────────────────────────────
    "ego_planner"|"ego-planner"|"EGO-Planner")
        log_info "Installing EGO-Planner-v2 (ZJU-FAST-Lab)..."

        if [[ -d "EGO-Planner-v2" ]]; then
            log_success "EGO-Planner-v2 already cloned"
        else
            if [[ "$ROS_VERSION" == "ROS2" ]]; then
                # Attempt ROS 2 branch
                log_info "Cloning EGO-Planner-v2 (ROS 2 branch)..."
                git clone --depth 1 -b ros2 \
                    https://github.com/ZJU-FAST-Lab/EGO-Planner-v2.git 2>/dev/null \
                    || {
                        log_warn "ROS 2 branch not found — cloning default branch"
                        git clone --depth 1 \
                            https://github.com/ZJU-FAST-Lab/EGO-Planner-v2.git
                    }
            else
                log_info "Cloning EGO-Planner-v2..."
                git clone --depth 1 https://github.com/ZJU-FAST-Lab/EGO-Planner-v2.git
            fi
            log_success "EGO-Planner-v2 cloned"
        fi

        # Core math/perception dependencies
        log_info "Installing EGO-Planner dependencies (Eigen3, PCL)..."
        sudo apt update
        apt_install_safe "libeigen3-dev" "libpcl-dev"

        # OSQP solver
        log_info "Installing OSQP solver..."
        if dpkg -l | grep -q "libosqp-dev"; then
            log_success "libosqp-dev already installed"
        else
            if apt-cache show "libosqp-dev" &> /dev/null 2>&1; then
                sudo apt install -y libosqp-dev
                log_success "libosqp-dev installed"
            else
                log_warn "libosqp-dev not in apt — building OSQP from source..."
                if [[ -d "osqp" ]]; then
                    log_success "OSQP source already present"
                else
                    git clone --depth 1 --recurse-submodules \
                        https://github.com/osqp/osqp.git
                    cmake -S osqp -B osqp/build \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DBUILD_SHARED_LIBS=ON
                    cmake --build osqp/build -- -j"$(nproc)"
                    sudo cmake --install osqp/build
                    log_success "OSQP built and installed from source"
                fi
            fi
        fi

        # osqp-eigen C++ wrapper
        if dpkg -l | grep -q "osqp-eigen" 2>/dev/null || \
           pkg-config --exists OsqpEigen 2>/dev/null; then
            log_success "osqp-eigen already installed"
        else
            if apt-cache show "osqp-eigen" &> /dev/null 2>&1; then
                sudo apt install -y osqp-eigen
                log_success "osqp-eigen installed"
            else
                log_warn "osqp-eigen not in apt — building from source..."
                if [[ -d "osqp-eigen" ]]; then
                    log_success "osqp-eigen source already present"
                else
                    git clone --depth 1 \
                        https://github.com/robotology/osqp-eigen.git
                    cmake -S osqp-eigen -B osqp-eigen/build \
                        -DCMAKE_BUILD_TYPE=Release
                    cmake --build osqp-eigen/build -- -j"$(nproc)"
                    sudo cmake --install osqp-eigen/build
                    log_success "osqp-eigen built and installed from source"
                fi
            fi
        fi

        run_rosdep
        ;;

    # ── 3. FUEL Exploration Planner ───────────────────────────────────────────
    "fuel"|"FUEL")
        if [[ "$ROS_VERSION" == "ROS2" ]]; then
            log_warn "FUEL is a ROS 1 package. ROS 2 support is not officially available."
            log_warn "Consider ego_planner or nav2 for ROS 2 exploration planning."
        fi

        log_info "Installing FUEL exploration planner (HKUST-Aerial-Robotics)..."

        if [[ -d "FUEL" ]]; then
            log_success "FUEL already cloned"
        else
            log_info "Cloning FUEL..."
            git clone --depth 1 --recurse-submodules \
                https://github.com/HKUST-Aerial-Robotics/FUEL.git
            log_success "FUEL cloned"
        fi

        # Math/perception base
        log_info "Installing FUEL dependencies (Eigen3, PCL)..."
        sudo apt update
        apt_install_safe "libeigen3-dev" "libpcl-dev"

        # NLopt — non-linear optimizer required by FUEL
        log_info "Installing NLopt..."
        if dpkg -l | grep -q "libnlopt-dev"; then
            log_success "libnlopt-dev already installed"
        else
            sudo apt update
            # libnlopt-cxx-dev may not exist on all distros — try both, warn on missing
            apt_install_safe "libnlopt-dev" "libnlopt-cxx-dev"
            log_success "NLopt installed"
        fi

        if [[ "$IS_ARM64" == "true" ]]; then
            log_warn "ARM64 (Jetson): NLopt apt package may be outdated."
            log_warn "If build fails, build NLopt from source:"
            log_warn "  https://github.com/stevengj/nlopt"
        fi

        run_rosdep
        ;;

    # ── 4. Navigation2 (ROS 2 only) ───────────────────────────────────────────
    "nav2"|"navigation2"|"Navigation2")
        if [[ "$ROS_VERSION" == "ROS1" ]]; then
            log_error "nav2 is ROS 2 only. For ROS 1, use 'waypoint_nav' or 'ego_planner'."
            exit 1
        fi

        log_info "Installing Navigation2 (nav2)..."
        sudo apt update

        if dpkg -l | grep -q "ros-${ROS_DISTRO}-navigation2"; then
            log_success "navigation2 already installed"
        else
            apt_install_safe \
                "ros-${ROS_DISTRO}-navigation2" \
                "ros-${ROS_DISTRO}-nav2-bringup"
            log_success "Navigation2 installed"
        fi

        # slam_toolbox — often needed alongside nav2 for GPS-denied mapping
        if dpkg -l | grep -q "ros-${ROS_DISTRO}-slam-toolbox"; then
            log_success "slam_toolbox already installed"
        else
            log_info "Installing slam_toolbox (nav2 companion for GPS-denied mapping)..."
            apt_install_safe "ros-${ROS_DISTRO}-slam-toolbox"
            log_success "slam_toolbox installed"
        fi
        ;;

    # ── 5. OctoMap 3D Occupancy Mapping ──────────────────────────────────────
    "octomap"|"OctoMap")
        log_info "Installing OctoMap 3D occupancy mapping..."
        sudo apt update

        if [[ "$ROS_VERSION" == "ROS1" ]]; then
            if dpkg -l | grep -q "ros-${ROS_DISTRO}-octomap "; then
                log_success "octomap (ROS 1) already installed"
            else
                apt_install_safe \
                    "ros-${ROS_DISTRO}-octomap" \
                    "ros-${ROS_DISTRO}-octomap-server" \
                    "ros-${ROS_DISTRO}-octomap-rviz-plugins" \
                    "ros-${ROS_DISTRO}-octomap-msgs"
                log_success "OctoMap (ROS 1) installed"
            fi
        else
            if dpkg -l | grep -q "ros-${ROS_DISTRO}-octomap "; then
                log_success "octomap (ROS 2) already installed"
            else
                apt_install_safe \
                    "ros-${ROS_DISTRO}-octomap" \
                    "ros-${ROS_DISTRO}-octomap-mapping" \
                    "ros-${ROS_DISTRO}-octomap-msgs"
                log_success "OctoMap (ROS 2) installed"
            fi
        fi
        ;;

    # ── Unknown ───────────────────────────────────────────────────────────────
    *)
        log_warn "Unknown planner type: $PLANNER_TYPE"
        log_info "Supported types:"
        log_info "  waypoint_nav  — MAVROS setpoint-based waypoint navigation"
        log_info "  super         — SUPER planner + ROG-Map (HKU-Mars, recommended for FAST-LIO)"
        log_info "  ommpc         — OMMPC controller for SUPER (body-rate MPC, high-speed tracking)"
        log_info "  rog_map       — ROG-Map standalone occupancy grid (replaces OctoMap)"
        log_info "  ego_planner   — EGO-Planner-v2 (ZJU-FAST-Lab, 3D trajectory)"
        log_info "  fuel          — FUEL exploration planner (HKUST, ROS 1)"
        log_info "  nav2          — Navigation2 (ROS 2 only)"
        log_info "  octomap       — OctoMap 3D occupancy mapping"
        exit 0
        ;;
esac

# ─────────────────────────────────────────────────────────────────────────────
# Summary
# ─────────────────────────────────────────────────────────────────────────────
echo ""
log_success "Path planner installation complete: $PLANNER_TYPE"
echo ""
log_info "Summary:"
log_info "  Planner   : $PLANNER_TYPE"
log_info "  ROS       : $ROS_VERSION ($ROS_DISTRO)"
log_info "  Workspace : $WORKSPACE_PATH"
echo ""
log_info "Next steps:"
if [[ "$ROS_VERSION" == "ROS1" ]]; then
    log_info "  Build workspace : cd $WORKSPACE_PATH && catkin build"
    log_info "  Source setup    : source $WORKSPACE_PATH/devel/setup.bash"
else
    log_info "  Build workspace : cd $WORKSPACE_PATH && colcon build"
    log_info "  Source setup    : source $WORKSPACE_PATH/install/setup.bash"
fi
log_info "  Verify install  : ros$([ "$ROS_VERSION" = "ROS1" ] && echo '' || echo '2') pkg list | grep -i planner"
